### ISSUE TITLE
a software that will make finding compatability problems 500x possibly more quick

### ISSUE THREAD

**Issue by exaltedkiller** [mborgerson/xemu#662]
### Feature Request

the name of the software is cheat engine
cheat engine lets you change the game speed from 2x to 500x more quick in the game
pretend the game is 12 hours long
pretend you change the speed to 30x 
you will be able to complete the game in 24 minutes
hack your health with cheat engine to try to dont die in the game
change the game speed movee in the game till you find a compatablity problem
save the game and exit cheat engine and exit the game so all the original game software structure goes back to its original state
 start the game again to the saved game now you at the compatablity problem with original software structure

you work 8 hours a day(pretend every game is 12 hours long) you will be able to complete 20 games a day
you will be able to complete 600 games in 30 days, in 2 mounths 1200 games will be completed

you emulator creator tell me if you will try this or anybody that knows how to fix game compatablity problems

download link for cheat engine
https://cheat-engine.en.uptodown.com/windows

**Comment by Spidy123222** [comment]
I get what your intentions Are but that assumes you can run the games better than normal speed. Just like how dolphin does it you have multiplier for speed but it ultimately requires you able to run that fast in the first place. It likely would make testing easier if your computer is fast enough to do that.

**Comment by binarymaster** [comment]
First of all, there are usually such things as game saves, so if you want to reproduce a bug that happens not at the game start, a game save helps.

Second, with such low-level emulator as xemu, it's possible to take full VM snapshots and load them later, in case a normal game save is not available (though there may be problems if you are about to change some internal structures in the source code while working on a bug fix).

Cheat Engine is actually helpful when you are doing a reverse engineering work of a game, but that's quite different topic.

**Comment by mborgerson** [comment]
Thanks for the request. There are no plans to support Cheat Engine. If you want to modify game state, you can use the built-in monitor or attach a debugger. You can also easily write scripts (with qmp, for instance) to hack on games, or build a proxy to use some other tool to modify the game state.
