### ISSUE TITLE
ALT+ENTER to toggle full screen.

### ISSUE THREAD

**Issue by gir489returns** [mborgerson/xemu#845]
### Feature Request

Currently it's some weird hotkey I've never heard of. ALT+ENTER has been the toggle fullscreen hotkey on Windows since I can remember. Maybe make this configurable? If this can be configured, please close this as PEBCAK.

### Alternatives

None.

### Additional Context

Signed: P. Enis.

**Comment by mborgerson** [comment]
UI key mapping for functions like this will be coming in the near future

**Comment by gir489returns** [comment]
> UI key mapping for functions like this will be coming in the near future

Awesome! The whole reason I even know of your project is I saw your eplc config on the IMGui brag issue ticket. You guys are doing amazing work. I just threw you a $20 on Patreon.
