### ISSUE TITLE
If no audio device detected, XEMU silently fails.

### ISSUE THREAD

**Issue by gir489returns** [mborgerson/xemu#846]
### Bug Description

1: Disable audio devices.
2: Launch XEMU

### Expected Behavior

A dialog box should display to let the user know there was no audio device detected.

Created QEMU launch parameters: C:\Users\Robert\Desktop\xemu.exe -machine xbox,bootrom=D:\New folder\xemustarter\XEMU FILES\Boot ROM Image\mcpx_1.0.bin,short-animation=on,kernel-irqchip=off -device smbus-storage,file=C:\Users\Robert\AppData\Roaming\xemu\xemu\eeprom.bin -bios D:\New folder\xemustarter\XEMU FILES\BIOS\Complex_4627.bin -m 64 -drive index=0,media=disk,file=D:\New folder\xemustarter\XEMU FILES\Xbox Hard Disk Image\xbox_hdd.qcow2,locked=on -drive index=1,media=cdrom,file=C:\Users\Robert\Desktop\nightfire.iso -display xemu -audiodev none,id=snd0 
xemu_version: 0.6.2-90-g6f507c80af
xemu_branch: master
xemu_commit: 6f507c80af546e0f5d316622d20f78820423ce6e
xemu_date: Wed Mar 23 00:38:13 UTC 2022
xemu_settings_get_path: config path: C:\Users\Robert\AppData\Roaming\xemu\xemu\xemu.ini
config_parse_callback: [system] flash_path = D:\New folder\xemustarter\XEMU FILES\BIOS\Complex_4627.bin
config_parse_callback: [system] bootrom_path = D:\New folder\xemustarter\XEMU FILES\Boot ROM Image\mcpx_1.0.bin
config_parse_callback: [system] hdd_path = D:\New folder\xemustarter\XEMU FILES\Xbox Hard Disk Image\xbox_hdd.qcow2
config_parse_callback: [system] eeprom_path = C:\Users\Robert\AppData\Roaming\xemu\xemu\eeprom.bin
config_parse_callback: [system] dvd_path = C:\Users\Robert\Desktop\nightfire.iso
config_parse_callback: [system] memory = 64
config_parse_callback: [system] shortanim = true
config_parse_callback: [system] hard_fpu = true
config_parse_callback: [audio] use_dsp = false
config_parse_callback: [display] scale = scale_ws169
config_parse_callback: [display] ui_scale = 1
config_parse_callback: [display] render_scale = 1
config_parse_callback: [display] window_width = 1280
config_parse_callback: [display] window_height = 960
config_parse_callback: [input] controller_1_guid = 030000004c050000cc09000000016800
config_parse_callback: [input] controller_2_guid = 
config_parse_callback: [input] controller_3_guid = 
config_parse_callback: [input] controller_4_guid = 
config_parse_callback: [network] enabled = true
config_parse_callback: [network] backend = user
config_parse_callback: [network] local_addr = 0.0.0.0:9368
config_parse_callback: [network] remote_addr = 1.2.3.4:9368
config_parse_callback: [network] pcap_iface = 
config_parse_callback: [misc] user_token = 
config_parse_callback: [misc] check_for_update = true
OS_Version: Windows
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 512.15
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
SDL_OpenAudioDevice failed

### xemu Version

Current github version.

### System Information

Windows 10.

**Comment by mborgerson** [comment]
Dup #354
